### ISSUE TITLE
Dividing by 0

### ISSUE THREAD

**Issue by mgratch** [hoaproject/Math#34]
I have tested this by using the example provided and replaced the expression with "100/0" and the value returned is false and an exception is not thrown.

https://github.com/hoaproject/Math/blob/master/Visitor/Arithmetic.php#L188
if I check for `intval($b)` then the exception is thrown as expected.

Thanks!

**Comment by Hywan** [comment]
@mgratch Hmm, possible! Do you have time to write a PR?

**Comment by Hywan** [comment]
I can reproduce. `var_dump(0 === (float) 0)` is false. Maybe we can either test with `0.0 === …` (because we manipulate reals). Casting to an integer is dangerous because `intval(0.1)` computes 0, so it's not correct to do that.

**Comment by Hywan** [comment]
Fixed by https://github.com/hoaproject/Math/pull/36.

**Comment by mgratch** [comment]
@Hywan Apparently I didn't realize this was still a problem for nested functions, I feel kind of foolish for missing it.  Please see #36. Thanks!
